# Generated by Django 5.0 on 2024-01-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('centre1', 'Centre 1'), ('centre2', 'Centre 2'), ('centre3', 'Centre 3')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Code_Client', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('ID_Fourni', models.AutoField(primary_key=True, serialize=False)),
                ('NomF', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('NomP', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Qte', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('CodeE', models.AutoField(primary_key=True, serialize=False)),
                ('NomE', models.CharField(max_length=100)),
                ('AdrE', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Tlf', models.IntegerField()),
                ('Salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('CodeAchat', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('date_achat', models.DateField()),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_achat_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.fournisseur')),
                ('matierePremiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement_Emloyes',
            fields=[
                ('CodePay', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('presence', models.BooleanField()),
                ('salaire_journalier', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_retenu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('masrouf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement_Fournisseur',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_reglement', models.DateField()),
                ('montant_versement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('CodeTransfert', models.AutoField(primary_key=True, serialize=False)),
                ('date_transfert', models.DateField()),
                ('quantite', models.IntegerField()),
                ('cout_transfert', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.centre')),
                ('matierePremiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.matierepremiere')),
            ],
        ),
    ]
