# Generated by Django 5.0 on 2024-01-07 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Code_Client', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('ID_Fourni', models.AutoField(primary_key=True, serialize=False)),
                ('NomF', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('NomP', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_achat', models.DateField()),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total_achat_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.fournisseur')),
                ('matierePremiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.matierepremiere')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement_Fournisseur',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_reglement', models.DateField()),
                ('montant_versement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField()),
                ('centre', models.CharField(choices=[('Centre 1', 'Centre 1'), ('Centre 2', 'Centre 2'), ('Centre 3', 'Centre 3')], max_length=100)),
                ('quantite', models.IntegerField()),
                ('cout_transfert_equivalent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matierePremiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.matierepremiere')),
            ],
        ),
    ]
