# Generated by Django 5.0 on 2024-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_emloyes',
            name='masrouf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement_emloyes',
            name='salaire_retenu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
