# Generated by Django 5.0 on 2023-12-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='nom',
            new_name='NomF',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='Nom',
            new_name='NomP',
        ),
    ]
