# Generated by Django 5.0 on 2023-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0002_rename_nom_fournisseur_nomf_rename_nom_produit_nomp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='produit',
        ),
        migrations.AddField(
            model_name='achat',
            name='produit',
            field=models.ManyToManyField(to='SystemeGestion.produit'),
        ),
    ]
