# Generated by Django 5.0 on 2024-01-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0003_creditclient_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='matierepremiere',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
