# Generated by Django 5.0 on 2024-01-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0003_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
