# Generated by Django 5.0 on 2023-12-30 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0003_remove_achat_produit_achat_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='produit',
        ),
        migrations.AddField(
            model_name='achat',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.produit'),
            preserve_default=False,
        ),
    ]
