# Generated by Django 5.0 on 2024-01-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0004_remove_achat_produit_achat_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
