# Generated by Django 5.0 on 2024-01-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0005_produit_prix_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='montant_reste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
