# Generated by Django 5.0 on 2024-01-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0007_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
