# Generated by Django 5.0 on 2024-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0008_alter_fournisseur_solde_alter_produit_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
