# Generated by Django 5.0 on 2024-01-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0009_alter_achat_montant_paye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='montant_reste',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='solde',
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
