# Generated by Django 5.0 on 2024-01-02 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0010_remove_achat_montant_reste_remove_fournisseur_solde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Reglement_Fournisseur',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_reglement', models.DateField()),
                ('montant_versement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.fournisseur')),
            ],
        ),
    ]
