# Generated by Django 5.0 on 2024-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0011_fournisseur_solde_reglement_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='montant_paye',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
