# Generated by Django 5.0 on 2024-01-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0012_alter_achat_montant_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement_fournisseur',
            name='achat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.achat'),
            preserve_default=False,
        ),
    ]
