# Generated by Django 5.0 on 2024-01-03 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0013_reglement_fournisseur_achat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('Code', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateField()),
                ('quantite', models.IntegerField()),
                ('cout_transfert_equivalent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.centre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SystemeGestion.produit')),
            ],
        ),
    ]
