# Generated by Django 5.0 on 2024-01-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0014_centre_transfert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='centre',
            field=models.CharField(choices=[('Centre 1', 'Centre 1'), ('Centre 2', 'Centre 2'), ('Centre 3', 'Centre 3')], max_length=100),
        ),
    ]
