# Generated by Django 5.0 on 2024-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0015_alter_transfert_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
