# Generated by Django 5.0 on 2024-01-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0016_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement_fournisseur',
            name='achat',
        ),
    ]
