# Generated by Django 5.0 on 2024-01-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SystemeGestion', '0017_remove_reglement_fournisseur_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_achat',
        ),
    ]
